







# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/queuedb?createDatabaseIfNotExist=true
spring.datasource.username=root

# here is password
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=QE5jUmZValhOcjI3dTh4L0E/RChnK0tiUGRTZ1ZrWXA=
jwt.expiration=86400000

# Server
server.port=8080