# MySQL (Aiven Cloud Database)
spring.datasource.url=jdbc:mysql://mysql-1f38606a-queuemaster123.f.aivencloud.com:25878/defaultdb?ssl-mode=REQUIRED
#spring.datasource.username=avnadmin
#spring.datasource.password=AVNS_caUkaV0zVR2_tV0nJbY
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
## JWT (DO NOT CHANGE)
#jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#jwt.expiration=86400000
#
##Server
#server.port=8080









# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/queuedb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=QE5jUmZValhOcjI3dTh4L0E/RChnK0tiUGRTZ1ZrWXA=
jwt.expiration=86400000

# Server
server.port=8080